gnn_config: 'craft_mol/gnn_config.json'
iupac_config: 'craft_mol/iupac_config.json'
selfies_config: 'craft_mol/selfies_config.json'
fusion_config: 'craft_mol/fusion_config.json'
train_config: 'craft_mol/train_config.json'


mol_width: 512
embed_dim: 256
batch_size: 32
temp: 0.07
msm_probability: 0.15
quene_size: 65536
momentum: 0.995
alpha: 0.4

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 10, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 10, cooldown_epochs: 0}